### ISSUE TITLE
check_dhcp: Compile issues for OpenWrt

### ISSUE THREAD

**Issue by lemoer** [FreifunkBremen/gatemon#13]
I just made a Gluon/OpenWrt package from check_dhcp, which results in two patches:
- To compile I have to specify `-D_GNU_SOURCE=1` externally, because of [this behaviour](http://git.musl-libc.org/cgit/musl/commit/include/netinet/udp.h?id=89511cd943d807b7fe31b61c06d4fe09888b8e9a) in musl.
- I have to rewrite the `gcc` directive your Makefile to `$(CC)`.

Are you willing to fix those in your repo or should I keep the patches outside?

By the way, my package Makefile can be found [here](https://paste.irrelefant.net/iePaeRu6.txt).

**Comment by ghost** [comment]
@jplitza meinung?

**Comment by jplitza** [comment]
Thanks for the feedback, @lemoer! I'm no good with Makefiles, thus I trust that `$(CC)` is reasonable here and changed that in 7b6e21d593cf535da7e4b795c69bbc2ad37cf321. To avoid `-D_GNU_SOURCE`, I simply used the BSD-style structure members in 2ffc0b32e7ccd41e2ebb29f58dd88ef48d6944d4, so that should be obsolete now as well. Please re-open if you find otherwise.

**Comment by lemoer** [comment]
Thank you. If I will have more feedback, I will get back to you.
